src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="comments")
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Post::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $post;

    /**
     * @ORM\ManyToOne(targetEntity=Dog::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $dog;

    /**
     * @ORM\Column(type="text")
     */
    private $comment_text;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPost(): ?Post
    {
        return $this->post;
    }

    public function setPost(?Post $post): self
    {
        $this->post = $post;

        return $this;
    }

    public function getDog(): ?Dog
    {
        return $this->dog;
    }

    public function setDog(?Dog $dog): self
    {
        $this->dog = $dog;

        return $this;
    }

    public function getCommentText(): ?string
    {
        return $this->comment_text;
    }

    public function setCommentText(string $comment_text): self
    {
        $this->comment_text = $comment_text;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use App\Service\RegistrationService;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="posts")
 * @ORM\Entity
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Dog::class, inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $dog;

    /**
     * @ORM\Column(type="text", nullable=false)
     */
    private $post_text;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="post", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDog(): ?dog
    {
        return $this->dog;
    }

    public function setDog(?Dog $dog): self
    {
        $this->dog = $dog;

        return $this;
    }

    public function getPostText(): ?string
    {
        return $this->post_text;
    }

    public function setPostText(string $post_text): self
    {
        $this->post_text = $post_text;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }
}

src/Controller/FeedController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Entity\Comment;
use App\Service\DogCRUDService;
use App\Service\CommentCRUDService;
use App\Service\PostCRUDService;
use App\Service\PackService;
use App\Form\PostFormType;
use App\Form\CommentFormType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class FeedController extends AbstractController
{
    public function index(
        DogCRUDService $dogService,
        PostCRUDService $postService,
        CommentCRUDService $commentService, 
        PackService $packService
        ): Response 
    {

        $dogUser = $this->getUser();

        $postAuthor = $dogService->getDogNiceName($dogUser);

        $posts = $dogService->getAllPosts($dogUser);
        
        $myPack = $packService->getPack($dogUser);

        if($myPack){
            $postsPack = $postService->getAllMyPackPosts($myPack);
            array_push($postsPack, $posts);
        }

        if(!$posts) {
            return $this->redirectToRoute('add_post');
        }

        $comments = $commentService->getAllCommentsByPosts($posts);

        $dogs = $dogService->getAllDogs();

        $otherDogUsers = $packService->getDogsNotInPack($dogUser, $myPack, $dogs);
        return $this->render(
            'feed/feed.html.twig', 
            [
                'posts' => $posts,
                'currentDogUserNiceName' => $postAuthor,
                'currentDogUser' => $dogUser,
                'comments' => $comments,
                'dogUsers' => $otherDogUsers,
                'myPack' => $myPack
            ]
        );
    }

    public function removePost(PostCRUDService $postService, Post $post): Response
    {
        $dogUser = $this->getUser();

        if($post->getDog() !== $dogUser) {
            return Response::HTTP_UNPROCESSABLE_ENTITY;
        }

        $postService->removePost($post);
        
        return $this->redirectToRoute('feed');
    }
    
    public function removeComment(CommentCRUDService $commentService, Comment $comment): Response
    {
        $dogUser = $this->getUser();

        if($comment->getDog() !== $dogUser) {
            return Response::HTTP_UNPROCESSABLE_ENTITY;
        }

        $commentService->removeComment($comment);
        
        return $this->redirectToRoute('feed');
    }

    public function createComment(Request $request, CommentCRUDService $commentService, Post $post) : Response
    {
        $comment = new Comment();
        
        $form = $this->createForm(CommentFormType::class, $comment);
        
        $dogUser = $this->getUser();

        $form->handleRequest($request);
        
        if($commentService->handleAddComment($comment, $post, $dogUser, $form)) {
            return $this->redirectToRoute('feed');
        }

        // Rendering the view if the form has not been submitted
        return $this->render(
            'feed/comment/add-comment.html.twig', 
            [
                'form' => $form->createView(),
            ]
        );
    }

    public function createPost(Request $request, PostCRUDService $postService): Response 
    {
        $post = new Post();

        $form = $this->createForm(PostFormType::class, $post);

        $dogUser = $this->getUser();
        $form->handleRequest($request);
        
        if($postService->handleAddPost($post, $dogUser, $form)) {
            return $this->redirectToRoute('feed');
        }

        // Rendering the view if the form has not been submitted
        return $this->render(
            'feed/post/add-post.html.twig',
            [
                'form' => $form->createView(),
            ]
        );
    }

    public function editPost(Request $request, PostCRUDService $postService, Post $post): Response 
    {
        $form = $this->createForm(PostFormType::class, $post);

        $form->handleRequest($request);
        
        if($postService->handleEditPost($post, $form)) {
            return $this->redirectToRoute('feed');
        }

        // Rendering the view if the form has not been submitted
        return $this->render(
            'feed/post/add-post.html.twig',
            [
                'form' => $form->createView(),
            ]
        );
    }

    public function editComment(Request $request, CommentCRUDService $commentService, Comment $comment): Response 
    {
        $form = $this->createForm(CommentFormType::class, $comment);

        $form->handleRequest($request);
        
        if($commentService->handleEditComment($comment, $form)) {
            return $this->redirectToRoute('feed');
        }

        // Rendering the view if the form has not been submitted
        return $this->render(
            'feed/post/add-post.html.twig',
            [
                'form' => $form->createView(),
            ]
        );
    }
}

templates/feed/feed.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="d-flex flex-row">
        <div class="feed__post_form">
            <div class="p-3 bg-white w-100 rounded my-3 pb-5">
                <div class="mb-3">
                    <strong class="text-capitalize">{{ currentDogUserNiceName }}</strong>
                </div>
                <a href="/add-post" type="button" class="w-100 border border-dark rounded feed__add_post">+</a>
            </div>
            {% for post in posts %}
                <div class="pe-2 pt-3 pb-2 bg-white w-100 my-3">
                    <div class="mb-3 feed__post_meta">
                        <strong class="text-capitalize">{{ post.dog.username }}</strong>
                        <a href="{{ path('remove_post', { id:post.id }) }}" type="button" class="border border-light rounded feed__form_button">remove</a>
                        <a href="{{ path('edit_post', { id:post.id }) }}" type="button" class="border border-light rounded feed__form_button">edit</a>
                    </div>
                    <p class="feed__post_body">{{ post.postText }}</p>
                    <div class="d-flex justify-content-between align-items-end">
                        <div>
                            <a href="{{ path('add_comment', { id:post.id }) }}" class="p-1 rounded feed__add_comment">Comment</a>
                        </div>
                        <button class="d-flex flex-row gap-2">
        
                            <p></p>
                            <img src="{{ asset('resources/images/thread.svg') }}">
                        </button>
                    </div>
                    <div class="d-flex flex-column">
                        {% for comment in comments %}
                            {% if comment.post.id is same as post.id %}
                            <div class="feed_comment">
                                <div class="mb-3 feed__comment_meta">
                                    <strong class="text-capitalize">{{ comment.dog.username }}</strong>
                                    <a href="{{ path('remove_comment', { id:comment.id }) }}" type="button" class="border border-light rounded feed__form_button">remove</a>
                                    <a href="{{ path('edit_comment', { id:comment.id }) }}" type="button" class="border border-light rounded feed__form_button">edit</a>
                                </div>
                                <p class="feed__post_body">{{ comment.commentText }}</p>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="w-100">

            <div>
                <h4>My Pack</h4>
                <div class="d-flex flex-column">
                    {% for dog in myPack %}
                        {% if dog.id is not same as currentDogUser.id %}
                        <div>
                            <strong class="text-capitalize">{{ dog.username }}</strong>
                            <a href="{{ path('remove_friend', { id:dog.id }) }}" type="button" class="border border-dark rounded feed__form_button">remove</a>
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <br>
            {% for dog in dogUsers %}
                <div class="d-flex flex-column">
                    <strong class="text-capitalize">{{ dog.username }}</strong>
                    <a href="{{ path('add_friend', { id:dog.id }) }}" class="p-1 rounded feed__add_comment">Add Friend</a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %} 